// flow-typed signature: d74eb80fc6379cde2a5fc91f235c4766
// flow-typed version: <<STUB>>/jshint-loader_v^0.8.3/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jshint-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jshint-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jshint-loader/example/entry' {
  declare module.exports: any;
}

declare module 'jshint-loader/example/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jshint-loader/example/entry.js' {
  declare module.exports: $Exports<'jshint-loader/example/entry'>;
}
declare module 'jshint-loader/example/webpack.config.js' {
  declare module.exports: $Exports<'jshint-loader/example/webpack.config'>;
}
declare module 'jshint-loader/index' {
  declare module.exports: $Exports<'jshint-loader'>;
}
declare module 'jshint-loader/index.js' {
  declare module.exports: $Exports<'jshint-loader'>;
}
