// flow-typed signature: fef15df71093aae366c60c1531eb129e
// flow-typed version: <<STUB>>/milligram_v^1.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'milligram'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'milligram' {
  declare module.exports: any;
}
